### ISSUE TITLE
Another element instead of button

### ISSUE THREAD

**Issue by dnish** [mikelpmc/react-multiline-clamping#8]
Hey,
would it be possible to add another element instead of the button, to expand the text?

**Comment by mikelpmc** [comment]
HI dnish,

I know I'm a little late but I was thinking on what you say and came up with what I think could be a flexible way of approach this use case you were mentioning.

I added two new props to pass down any element you want as the show more/less buttons, that way its the responsability of the consumer to decide what element he wants to use there, can be anything, even another components as long as you pass the `toggle` action to the onClick handler it would work.

Example:

```js
 <Clamp
       withToggle
        showMoreElement={({ toggle }) => (
            <span role="button" onClick={toggle}>
                Show more
            </button>
        )}
        showLessElement={({ toggle }) => (
            <span role="button" onClick={toggle}>
                Show less
            </span>
        )}
    >
        <p>{text}</p>
    </Clamp>
```
You can see the change on this PR https://github.com/mikelpmc/react-multiline-clamping/pull/19

I would love to have feedback on this and know if this fits your use case as I plan to merge and publish a new version in a shortime with these changes.

Thanks a lot and forgive me again for taking so long to respond.

**Comment by mikelpmc** [comment]
Closing this issue, resolved on this PR: https://github.com/mikelpmc/react-multiline-clamping/pull/19
